// @ahaslides-product/design/canvas — the canvas surface entry (generated by generate.mjs from guidelines/canvas.json; do not edit by hand).
// ONE import registers the <aha-*> elements the canvas surface uses. Load the token layer separately:
//   <link rel="stylesheet" href=".../lib/tokens.css">   or   import '@ahaslides-product/design/tokens.css'
import './aha-autocomplete.js';
import './aha-button.js';
import './aha-chart.js';
import './aha-status-icon.js';
import './aha-stepper.js';
import './aha-tooltip.js';
import './icons.js';
